version: 2
updates:
  # Go modules in root
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"

  # Dockerfile in root
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:15"
      timezone: "UTC"
    commit-message:
      prefix: "deps"
      include: "scope"

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:30"
      timezone: "UTC"
    commit-message:
      prefix: "deps"
      include: "scope"

  # Helm chart dependencies (if any Chart.yaml has dependencies)
  - package-ecosystem: "helm"
    directory: "/chart/ipam-api"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:45"
      timezone: "UTC"
    commit-message:
      prefix: "deps"
      include: "scope"
    ignore:
      - dependency-name: "mongodb"
        update-types: ["version-update:semver-major"]

  # Future: npm example (uncomment if JS client added)
  # - package-ecosystem: "npm"
  #   directory: "/web"
  #   schedule:
  #     interval: "weekly"
  #     day: "sunday"
  #     time: "03:00"
  #     timezone: "UTC"
