apiVersion: v1
kind: Secret
metadata:
  name: ipam-config-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  config: |
    {
      "mongodb": {
        "username": "{{ .Values.ipamConfig.mongodb.username }}",
        "password_path": "mongodb.secret",
        "host": "{{ .Values.ipamConfig.mongodb.host }}",
        "port": 27017,
        "database": "{{ .Values.ipamConfig.mongodb.database }}",
        "collection": "{{ .Values.ipamConfig.mongodb.collection }}"
      },
      "netbox": {
        "url": "{{ .Values.ipamConfig.netbox.url }}",
        "token_path": "netbox.secret",
        "constraint_tag": "vitistack"
      },
      "encryption_secrets": {
        "path": "secrets.json"
      },
      "splunk": {
        "enable": true,
        "url": "https://splunk-hec.nhn.no",
        "token_path": "splunk.secret",
        "index": "vitistack",
        "source": "vitistack:ipam-api",
        "sourcetype_app": "ipam-api:app",
        "sourcetype_http": "ipam-api:http"
      }
    }
