apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: ipam-api
  namespace: {{ .Values.mongodb.namespace }}
spec:
  members: {{ .Values.mongodb.replicaCount }}
  type: ReplicaSet
  version: {{ .Values.mongodb.version }}
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: admin
      passwordSecretRef: # reference to the secret below to generate user password
        name: ipam-api-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: "readWriteAnyDatabase"
          db: "admin"
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    net:
      port: {{ .Values.mongodb.service.port }}
  statefulSet:
      spec:
        template:
              spec:
                containers:
                  - name: mongod
                    resources:
                      requests:
                        cpu: "500m"
                        memory: "1Gi"
                      limits:
                        cpu: "2"
                        memory: "2Gi"
                    securityContext:
                      allowPrivilegeEscalation: false
                      capabilities:
                        drop: ["ALL"]
                      runAsNonRoot: true
                      runAsUser: 999
                      seccompProfile:
                        type: RuntimeDefault
                  - name: mongodb-agent
                    resources:
                      requests:
                        cpu: "100m"
                        memory: "200Mi"
                      limits:
                        cpu: "500m"
                        memory: "500Mi"
                    securityContext:
                      allowPrivilegeEscalation: false
                      capabilities:
                        drop: ["ALL"]
                      runAsNonRoot: true
                      runAsUser: 999
                      seccompProfile:
                        type: RuntimeDefault
        volumeClaimTemplates:
          - metadata:
              name: data-volume
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: {{ .Values.mongodb.volumes.data }}
          - metadata:
              name: logs-volume
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: {{ .Values.mongodb.volumes.logs }}