apiVersion: v1
kind: Secret
metadata:
  name: ipam-encrypt-json-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  secrets.json: |
    {
      "enc_key": "{{ .Values.encryption.encKey }}",
      "enc_iv": "{{ .Values.encryption.encIv }}"
    }
