apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipam-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ipam
  template:
    metadata:
      labels:
        app: ipam
    spec:
      containers:
        - name: ipam-api
          image: {{ .Values.ipamApi.image }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: ipam-config
              mountPath: /app/config
              subPath: config
            - name: ipam-encrypt-json-secret
              mountPath: /app/secrets.json
              subPath: secrets.json
            - name: mongo-secret
              mountPath: /app/mongodb.secret
              subPath: mongodb.secret
            - name: netbox-secret
              mountPath: /app/netbox.secret
              subPath: netbox.secret
            - name: splunk-secret
              mountPath: /app/splunk.secret
              subPath: splunk.secret
      volumes:
        - name: ipam-config
          secret:
            secretName: ipam-config-secret
        - name: ipam-encrypt-json-secret
          secret:
            secretName: ipam-encrypt-json-secret
        - name: mongo-secret
          secret: 
            secretName: ipam-secret-mongo
        - name: netbox-secret
          secret:
            secretName: ipam-secret-netbox
        - name: splunk-secret
          secret:
            secretName: ipam-secret-splunk
