apiVersion: v1
kind: Secret
metadata:
  name: ipam-api-password
  namespace: mongodb
type: Opaque
stringData:
  password: {{ .Values.secrets.mongodb | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ipam-secret-mongo
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  mongodb.secret: {{ .Values.secrets.mongodb | quote }}
