definitions:
  apicontracts.HTTPError:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  apicontracts.IpamApiRequest:
    properties:
      address:
        type: string
      ip_family:
        enum:
        - ipv4
        - ipv6
        example: ipv4
        type: string
      new_secret:
        type: string
      secret:
        example: a_secret_value
        maxLength: 64
        minLength: 8
        type: string
      service:
        $ref: '#/definitions/apicontracts.Service'
      zone:
        example: inet
        type: string
    required:
    - ip_family
    - secret
    - zone
    type: object
  apicontracts.IpamApiResponse:
    properties:
      address:
        type: string
      message:
        type: string
      secret:
        type: string
      zone:
        type: string
    type: object
  apicontracts.Service:
    properties:
      cluster_id:
        example: 123e4567-e89b-12d3-a456-426614174000
        type: string
      deny_external_cleanup:
        type: boolean
      expires_at:
        example: "2025-06-03 14:39:31.546230273"
        type: string
      namespace_id:
        example: 123e4567-e89b-12d3-a456-426614174000
        type: string
      retention_period_days:
        type: integer
      service_name:
        example: service1
        type: string
    required:
    - cluster_id
    - namespace_id
    - service_name
    type: object
info:
  contact: {}
paths:
  /:
    delete:
      consumes:
      - application/json
      description: Set expiration for a service
      parameters:
      - description: Request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/apicontracts.IpamApiRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apicontracts.IpamApiResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apicontracts.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apicontracts.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apicontracts.HTTPError'
      summary: Set expiration for a service
      tags:
      - addresses
    post:
      consumes:
      - application/json
      description: Register an address in Vitistack IPAM API
      parameters:
      - description: Request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/apicontracts.IpamApiRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apicontracts.IpamApiResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apicontracts.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apicontracts.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apicontracts.HTTPError'
      summary: Register an address
      tags:
      - addresses
swagger: "2.0"
